In [1]:
import torch
import numpy as np

log = lambda t:print(t.size(), '\n', t)

x = torch.LongTensor(np.arange(2*3*4)).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [4]:
print(x[0,0])
print(x[1,2])
print(torch.cat((x[0,0].unsqueeze(0), x[1,2].unsqueeze(0)), dim=0))

tensor([0, 1, 2, 3])
tensor([20, 21, 22, 23])
tensor([[ 0,  1,  2,  3],
        [20, 21, 22, 23]])


In [6]:
index1 = [0,1] # np.array([0,1]) / torch.LongTensor([0,1])在这里结果是一样的
index2 = [0,2]
x[index1, index2]

tensor([[ 0,  1,  2,  3],
        [20, 21, 22, 23]])

In [7]:
index = torch.LongTensor([[0,1], [0,2]])
x[index]

IndexError: index 2 is out of bounds for dimension 0 with size 2

In [8]:
index = torch.LongTensor([[0,1], [0,1]])
x[index].size()

torch.Size([2, 2, 3, 4])

In [24]:
(x.index_select(dim=1, index=torch.LongTensor([0])).squeeze(1) == \
torch.cat((x[0,0].unsqueeze(0), x[1,0].unsqueeze(0)), dim=0)).all()

tensor(True)